### ISSUE TITLE
Post job cleanup: unexpected end of file

### ISSUE THREAD

**Issue by TheTumultuousUnicornOfDarkness** [hummeltech/vagrant-action#4]
Since we updated out actions to @v4, *Post provision VM* fail with the following error:
```
Post job cleanup.
Post job cleanup.
Post job cleanup.
$ if [ ! -f /tmp/packaged.box ]; then
/bin/bash: -c: line 2: syntax error: unexpected end of file
Error: The process '/bin/bash' failed with exit code 2
```

Jobs:
- FreeBSD: https://github.com/anrieff/libcpuid/actions/runs/13907790736/job/38914786395
- NetBSD: https://github.com/anrieff/libcpuid/actions/runs/13907790724/job/38914785696
- OpenBSD: https://github.com/anrieff/libcpuid/actions/runs/13907790735/job/38914785874

**Comment by hummeltech** [comment]
Thanks for the report, I think this should be resolved now with the latest commit (https://github.com/hummeltech/vagrant-action/commit/5f914e0265d60258568f99f67c37a4bd261650ea). I will need to add a test for box caching.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
That is better for FreeBSD and NetBSD but it is still failing on OpenBSD: https://github.com/anrieff/libcpuid/actions/runs/13907790735/job/38988953608

**Comment by hummeltech** [comment]
Thanks for the report update, it looks like the issue was caused by `virt-sysprep` not being installed for `libvirt` image exports. VirtualBox-provided systems already have the requisite tool for image exports installed, so you weren't experiencing that previously. I have added the installation of the `libguestfs-tools` to Ubuntu host runners using the `libvirt` provider in order to satisfy the requirement. I have also added a test to help ensure expected functionality.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
All right now, everything is fine. Thank you very much.
